[package]
name = "dbpod"
version = "0.1.0"
description = "DBPod PostgreSQL client"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "dbpod_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "tls-rustls-ring-native-roots", "postgres", "uuid", "chrono", "json", "rust_decimal", "ipnetwork", "mac_address", "bigdecimal"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-util = "0.7.19"
ts-rs = { version = "12.0.1", features = ["uuid-impl", "chrono-impl"] }
uuid = { version = "1.26.0", features = ["v4", "serde"] }
thiserror = "2.0.20"
chrono = "0.4.45"
keyring = "4.2.0"
futures-util = "0.3.34"
base64 = "0.23.1"
tauri-plugin-dialog = "2.7.3"

[dev-dependencies]
base64 = "0.23.1"
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }

